# Site settings
title: Jason'Blog
email: depblugz@gmail.com
description: >-
  We can only see a short distance ahead, 
  but we can see plenty there that needs to be done！
baseurl: "/myblog"
url: "https://JasonDepblu.github.io"
github_username: Jason

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-read-time

# Syntax highlighting
highlighter: rouge

# Sass settings
sass:
  style: compressed

# Default layout settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "index.html"
    values:
      layout: "home"

kramdown:
  syntax_highlighter_opts:
    block: true
    inline: true
  input: GFM

collections:
  navigation:
    output: true

markdown: kramdown

excerpt_separator: "<!--more-->"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
