title: Your Site Title
email: your-email@example.com
description: >-
  Your site description.
baseurl: "" # Set to empty string for root path or "/myblog" for subfolder
url: "" # the base hostname & protocol for your site
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
