[build]
  # Set the directory to publish
  publish = "_site"

  # Set the directory that contains the functions
  functions = "netlify/functions"

# Set up redirects for the functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true