[build.environment]
  RUBY_VERSION = "3.3.5"

[build]
  command = "./build-integrated.sh" # "jekyll build " # && npm run build:chat
#  pubilish = "build"
  publish = "_site"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  command = "npm run dev"
  port = 8080
  targetPort = 8889
  publish = "/chat"
  framework = "jekyll"
#  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[functions.rag]
  timeout = 60

[functions.status]
  timeout = 60

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
#  force = false

[[redirects]]
  from = "/chat/*"
  to = "/chat/index.html"
  status = 200