[build.environment]
  RUBY_VERSION = "3.3.5"
#  PYTHON_VERSION = "3.10"

[build]
  publish = "_site"
  functions = "netlify/functions"

[dev]
  publish = "_site"
  functions = "netlify/functions"
  # Specify framework to avoid auto-detection issues
#  framework = "#custom"

[functions]
  directory = "netlify/functions"
  # This pattern tells Netlify to include .py files and requirements.txt
#  included_files = ["netlify/functions/**/*.py", "netlify/functions/**/requirements.txt"]

#[functions.environment]
#  PYTHON_VERSION = "3.11"

[functions.rag]
  timeout = 60

[functions.status]
  timeout = 30

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
#  to = "http://localhost:8000/api/:splat"
  status = 200
  force = true

#[[redirects]]
#  from = "/myblog/*"
#  to = "/:splat"
#  status = 301
#  force = true
