[build.environment]
  RUBY_VERSION = "3.3.5"

[build]
  publish = "_site"
  functions = "netlify/functions"

[dev]
  publish = "_site"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[functions.rag]
  timeout = 60

[functions.status]
  timeout = 30

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# 这是重要的一步 - 确保 _site 目录中的文件被正确提供
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false