[build.environment]
  RUBY_VERSION = "3.3.5"

[build]
  publish = "_site"
  functions = "netlify/functions"

[dev]
  publish = "_site"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[functions.rag-background]
  timeout = 30

[functions.status-background]
  timeout = 10

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false