[build.environment]
  RUBY_VERSION = "3.2.2"
  PYTHON_VERSION = "3.11"

[build]
  publish = "_site"
  functions = "netlify/functions"

[dev]
  publish = "_site"
  functions = "netlify/functions"
  # Specify framework to avoid auto-detection issues
#  framework = "#custom"

[functions]
  directory = "netlify/functions"

[functions.environment]
  PYTHON_VERSION = "3.11"

[functions.rag]
  timeout = 60

[functions.status]
  timeout = 30

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/myblog/*"
  to = "/:splat"
  status = 301
  force = true
